# Generated by Django 3.2.3 on 2021-05-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0002_auto_20210527_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorstatic',
            name='course',
        ),
        migrations.AddField(
            model_name='professorstatic',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Vote.course'),
        ),
    ]
