# Generated by Django 3.2.3 on 2021-05-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0004_auto_20210527_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Vote.professorstatic'),
        ),
    ]
