# Generated by Django 3.2.3 on 2021-05-28 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vote', '0005_alter_poll_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Vote.professorstatic'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
